jwt:
  issuer: "deck-project"
deck:
  gateway:
    url: "http://localhost:8090/api"
  users:
    url: ${deck.gateway.url}/users
access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
