server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: discussions
          uri: lb://discussions
          predicates:
            - Path=/api/discussions/**
          filters:
            - StripPrefix=2
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
